// =========================================================
// /api/download.js
// Generates PDF or DOCX of the brand strategy
// =========================================================

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { format } = req.query;
  const { results, formData } = req.body;

  if (!results || !formData) {
    return res.status(400).json({ error: 'Missing results or formData' });
  }

  const name = (formData.yourName || 'My').replace(/[^a-zA-Z0-9 ]/g, '');
  const archetype = (formData.archetypeMain || 'Brand').replace(/[^a-zA-Z0-9 ]/g, '');

  if (format === 'docx') {
    return generateDocx(req, res, results, formData, name, archetype);
  } else {
    return generatePdf(req, res, results, formData, name, archetype);
  }
}

// ─── DOCX GENERATION ─────────────────────────────────────
async function generateDocx(req, res, r, fd, name, archetype) {
  try {
    const { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, Packer, BorderStyle } = await import('docx');

    const doc = new Document({
      creator: 'Flourish Online Brand Kick Start Generator',
      title: `${name} — ${archetype} Brand Strategy`,
      description: 'Personalised brand strategy generated by Flourish Online',
      styles: {
        default: {
          document: {
            run: { font: 'Calibri', size: 24 },
            paragraph: { spacing: { after: 160 } },
          },
        },
      },
      sections: [{
        properties: {},
        children: buildDocxContent(r, fd, name, archetype, { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle }),
      }],
    });

    const buffer = await Packer.toBuffer(doc);
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${name}_${archetype}_Brand_Strategy.docx"`);
    return res.send(buffer);
  } catch (err) {
    console.error('DOCX error:', err);
    return res.status(500).json({ error: 'Failed to generate Word document.' });
  }
}

function buildDocxContent(r, fd, name, archetype, { Paragraph, TextRun, HeadingLevel, AlignmentType }) {
  const children = [];
  const h = (text, level) => new Paragraph({ text, heading: level, thematicBreak: false });
  const p = (text) => new Paragraph({ children: [new TextRun({ text: text || '', break: 0 })] });
  const br = () => new Paragraph({ text: '' });
  const bullet = (text) => new Paragraph({ text, bullet: { level: 0 } });
  const bold = (label, value) => new Paragraph({
    children: [new TextRun({ text: label, bold: true }), new TextRun({ text: value || '' })],
  });

  // Cover
  children.push(new Paragraph({
    children: [new TextRun({ text: `${name}'s Brand Kick Start`, bold: true, size: 52 })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 400, after: 200 },
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: `${archetype} Archetype · Generated by Flourish Online`, size: 24, color: 'BE1650' })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 600 },
  }));

  // 1. Foundation
  children.push(h('1. Brand Foundation', HeadingLevel.HEADING_1), br());
  children.push(h('Your Why', HeadingLevel.HEADING_2));
  children.push(p(r.brandFoundation?.why));
  children.push(h('Your Vision', HeadingLevel.HEADING_2));
  children.push(p(r.brandFoundation?.vision));
  children.push(h('Your Mission', HeadingLevel.HEADING_2));
  children.push(p(r.brandFoundation?.mission), br());

  // 2. Values
  children.push(h('2. Your Values', HeadingLevel.HEADING_1), br());
  children.push(h('Core Brand Values', HeadingLevel.HEADING_2));
  (r.values?.core3 || []).forEach(v => children.push(bullet(v)));
  children.push(h('Top 10 Values', HeadingLevel.HEADING_2));
  (r.values?.top10 || []).forEach(v => children.push(bullet(v)));
  children.push(h('Core Value Statements', HeadingLevel.HEADING_2));
  (r.values?.coreValueStatements || []).forEach(s => children.push(p(`→ ${s}`)));
  children.push(br());

  // 3. Weird
  children.push(h("3. Your Weird", HeadingLevel.HEADING_1), br());
  children.push(h('What Makes You Unique', HeadingLevel.HEADING_2));
  children.push(p(r.weird?.uniqueness));
  children.push(h('What You Do', HeadingLevel.HEADING_2));
  (r.weird?.doList || []).forEach(i => children.push(bullet(`✓ ${i}`)));
  children.push(h("What You Don't Do", HeadingLevel.HEADING_2));
  (r.weird?.dontList || []).forEach(i => children.push(bullet(`✗ ${i}`)));
  children.push(h('Your Superpower', HeadingLevel.HEADING_2));
  children.push(p(r.weird?.superpower));
  children.push(h('Your Archnemesis', HeadingLevel.HEADING_2));
  children.push(p(r.weird?.archnemesisName));
  children.push(p(r.weird?.archnemesisDescription));
  children.push(h('Brand Personality', HeadingLevel.HEADING_2));
  children.push(p((r.weird?.brandPersonality || []).join(' · ')));
  children.push(br());

  // 4. Ideal Client
  children.push(h('4. Your People', HeadingLevel.HEADING_1), br());
  children.push(h(r.idealClient?.name || 'Your Dream Client', HeadingLevel.HEADING_2));
  children.push(p(r.idealClient?.description));
  children.push(h('Their Challenges', HeadingLevel.HEADING_2));
  (r.idealClient?.challenges || []).forEach(c => children.push(bullet(c)));
  children.push(h('What They Really Want', HeadingLevel.HEADING_2));
  (r.idealClient?.motivations || []).forEach(m => children.push(bullet(m)));
  children.push(h('Real Quotes', HeadingLevel.HEADING_2));
  (r.idealClient?.realQuotes || []).forEach(q => children.push(p(`"${q}"`)));
  children.push(h('Marketing Messages That Land', HeadingLevel.HEADING_2));
  (r.idealClient?.marketingMessages || []).forEach(m => children.push(bullet(m)));
  children.push(br());

  // 5. Messaging
  children.push(h('5. Brand Messaging', HeadingLevel.HEADING_1), br());
  children.push(h('Tagline Options', HeadingLevel.HEADING_2));
  (r.taglines || []).forEach(t => children.push(p(`→ ${t}`)));
  children.push(h('Value Proposition', HeadingLevel.HEADING_2));
  children.push(p(r.messaging?.valueProposition));
  children.push(h('Elevator Pitch', HeadingLevel.HEADING_2));
  children.push(p(r.messaging?.elevatorPitch));
  children.push(br());

  // 6. Brand Story
  children.push(h('6. Brand Story', HeadingLevel.HEADING_1), br());
  (r.brandStory || '').split('\n\n').forEach(para => children.push(p(para)));
  children.push(br());

  // 7. Social Bio
  children.push(h('7. Social Bio', HeadingLevel.HEADING_1), br());
  children.push(h('Short Bio (Instagram/TikTok)', HeadingLevel.HEADING_2));
  children.push(p(r.socialBio?.short));
  children.push(h('Long Bio (LinkedIn/Website)', HeadingLevel.HEADING_2));
  children.push(p(r.socialBio?.long));
  children.push(br());

  // 8. Content Pillars
  children.push(h('8. Content Pillars', HeadingLevel.HEADING_1), br());
  (r.contentPillars || []).forEach(cp => {
    children.push(h(cp.pillar || '', HeadingLevel.HEADING_2));
    children.push(p(cp.description));
    children.push(new Paragraph({ children: [new TextRun({ text: 'Content Ideas:', bold: true })] }));
    (cp.postIdeas || []).forEach(idea => children.push(bullet(idea)));
    children.push(br());
  });

  // 9. Offer Structure
  children.push(h('9. Offer Structure', HeadingLevel.HEADING_1), br());
  children.push(h('Your Offers Reviewed', HeadingLevel.HEADING_2));
  children.push(p(r.offerStructure?.review));
  children.push(h('Recommended Offer Suite', HeadingLevel.HEADING_2));
  (r.offerStructure?.recommendedSuite || []).forEach(offer => {
    children.push(new Paragraph({ children: [new TextRun({ text: `${offer.tier}: ${offer.name}`, bold: true })] }));
    children.push(p(offer.description));
  });
  children.push(h('Key Refinements', HeadingLevel.HEADING_2));
  (r.offerStructure?.refinements || []).forEach(ref => children.push(bullet(ref)));
  children.push(br());

  // 10. 90-Day Plan
  children.push(h('10. Your 90-Day Plan', HeadingLevel.HEADING_1), br());
  children.push(p(r.ninetyDayPlan?.intro));
  (r.ninetyDayPlan?.weeks || []).forEach(week => {
    children.push(h(week.theme || '', HeadingLevel.HEADING_2));
    (week.tasks || []).forEach(task => children.push(bullet(task)));
    children.push(br());
  });

  return children;
}

// ─── PDF GENERATION (HTML-to-print) ──────────────────────
async function generatePdf(req, res, r, fd, name, archetype) {
  // Generate HTML and return it as a print-ready HTML file
  // Users can open it and Ctrl+P / Cmd+P to save as PDF
  const html = buildPdfHtml(r, fd, name, archetype);

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Content-Disposition', `inline; filename="${name}_${archetype}_Brand_Strategy.html"`);
  return res.send(html);
}

function buildPdfHtml(r, fd, name, archetype) {
  const esc = (s) => String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const list = (items) => items && items.length
    ? `<ul>${items.map(i => `<li>${esc(i)}</li>`).join('')}</ul>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${esc(name)} — ${esc(archetype)} Brand Strategy</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #193133; background: white; padding: 40px; }
  h1 { font-size: 28pt; color: #BE1650; margin: 0 0 8px; }
  h2 { font-size: 16pt; color: #BE1650; border-bottom: 2px solid #BE1650; padding-bottom: 6px; margin: 32px 0 16px; }
  h3 { font-size: 13pt; font-weight: bold; margin: 20px 0 8px; }
  h4 { font-size: 10pt; font-weight: bold; text-transform: uppercase; letter-spacing: 0.1em; color: #BE1650; margin: 16px 0 6px; }
  p { margin-bottom: 10px; }
  ul { margin: 0 0 12px 20px; }
  li { margin-bottom: 4px; }
  .cover { text-align: center; padding: 60px 0 40px; border-bottom: 2px solid #193133; margin-bottom: 40px; }
  .subtitle { font-size: 13pt; color: #BE1650; margin-top: 4px; }
  blockquote { border-left: 3px solid #BE1650; padding: 8px 16px; font-style: italic; color: #5A5A5A; margin: 12px 0; }
  .tagline-opt { padding: 10px 14px; background: #EDE8DF; border-left: 3px solid #BE1650; margin-bottom: 8px; font-style: italic; }
  .do-dont { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 12px 0; }
  .do-col, .dont-col { padding: 14px; border: 1px solid #D5D5D5; }
  .do-col { border-top: 3px solid #1A7A4A; }
  .dont-col { border-top: 3px solid #BE1650; }
  .values-row { display: flex; flex-wrap: wrap; gap: 6px; margin: 8px 0 16px; }
  .val-pill { padding: 3px 10px; font-size: 10pt; font-weight: bold; }
  .val-pill.core { background: #570021; color: white; }
  .val-pill.top10 { background: #193133; color: white; }
  @media print {
    body { padding: 20px; }
    h2 { page-break-before: always; }
    h2:first-of-type { page-break-before: avoid; }
    .cover { page-break-after: always; }
  }
</style>
</head>
<body>
<div class="cover">
  <h1>${esc(name)}'s Brand Kick Start</h1>
  <p class="subtitle">${esc(archetype)} Archetype · Generated by Flourish Online</p>
  <p style="margin-top:8px;color:#5A5A5A;font-size:10pt;">Print this page or save as PDF using Ctrl+P / Cmd+P → Save as PDF</p>
</div>

<h2>1. Brand Foundation</h2>
<h3>Your Why</h3><p>${esc(r.brandFoundation?.why)}</p>
<h3>Your Vision</h3><p>${esc(r.brandFoundation?.vision)}</p>
<h3>Your Mission</h3><p>${esc(r.brandFoundation?.mission)}</p>

<h2>2. Your Values</h2>
<h3>Core Brand Values</h3>
<div class="values-row">${(r.values?.core3||[]).map(v=>`<span class="val-pill core">${esc(v)}</span>`).join('')}</div>
<h3>Top 10 Values</h3>
<div class="values-row">${(r.values?.top10||[]).map(v=>`<span class="val-pill top10">${esc(v)}</span>`).join('')}</div>
<h3>Core Value Statements</h3>
${(r.values?.coreValueStatements||[]).map(s=>`<p>→ ${esc(s)}</p>`).join('')}

<h2>3. Your Weird</h2>
<h3>What Makes You Unique</h3><p>${esc(r.weird?.uniqueness)}</p>
<div class="do-dont">
  <div class="do-col"><h4>We Do</h4>${list(r.weird?.doList)}</div>
  <div class="dont-col"><h4>We Don't Do</h4>${list(r.weird?.dontList)}</div>
</div>
<h3>Your Superpower</h3><p>${esc(r.weird?.superpower)}</p>
<h3>Your Archnemesis</h3><p><strong>${esc(r.weird?.archnemesisName)}</strong></p><p>${esc(r.weird?.archnemesisDescription)}</p>
<h3>Brand Personality</h3><p>${(r.weird?.brandPersonality||[]).map(t=>`<strong>${esc(t)}</strong>`).join(' · ')}</p>

<h2>4. Your People</h2>
<h3>${esc(r.idealClient?.name || 'Your Dream Client')}</h3><p>${esc(r.idealClient?.description)}</p>
<h3>Their Challenges</h3>${list(r.idealClient?.challenges)}
<h3>What They Really Want</h3>${list(r.idealClient?.motivations)}
<h3>Real Quotes</h3>${(r.idealClient?.realQuotes||[]).map(q=>`<blockquote>"${esc(q)}"</blockquote>`).join('')}
<h3>Marketing Messages</h3>${list(r.idealClient?.marketingMessages)}

<h2>5. Brand Messaging</h2>
<h3>Tagline Options</h3>${(r.taglines||[]).map(t=>`<div class="tagline-opt">${esc(t)}</div>`).join('')}
<h3>Value Proposition</h3><p>${esc(r.messaging?.valueProposition)}</p>
<h3>Elevator Pitch</h3><p>${esc(r.messaging?.elevatorPitch)}</p>

<h2>6. Brand Story</h2>
${(r.brandStory||'').split('\n\n').map(para=>`<p>${esc(para)}</p>`).join('')}

<h2>7. Social Bio</h2>
<h3>Short Bio (Instagram / TikTok)</h3><p>${esc(r.socialBio?.short)}</p>
<h3>Long Bio (LinkedIn / Website)</h3><p>${esc(r.socialBio?.long).replace(/\n/g,'</p><p>')}</p>

<h2>8. Content Pillars</h2>
${(r.contentPillars||[]).map(cp=>`
  <h3>${esc(cp.pillar)}</h3>
  <p>${esc(cp.description)}</p>
  <h4>Content Ideas</h4>${list(cp.postIdeas)}
`).join('')}

<h2>9. Offer Structure</h2>
<h3>Your Offers Reviewed</h3><p>${esc(r.offerStructure?.review)}</p>
<h3>Recommended Offer Suite</h3>
${(r.offerStructure?.recommendedSuite||[]).map(o=>`<p><strong>${esc(o.tier)}: ${esc(o.name)}</strong><br>${esc(o.description)}</p>`).join('')}
<h3>Key Refinements</h3>${list(r.offerStructure?.refinements)}

<h2>10. Your 90-Day Plan</h2>
<p>${esc(r.ninetyDayPlan?.intro)}</p>
${(r.ninetyDayPlan?.weeks||[]).map((w,i)=>`
  <h3>Week ${i+1} · ${esc(w.theme)}</h3>${list(w.tasks)}
`).join('')}

</body></html>`;
}
